monitor:
  hello: monitor-local--66666


server:
  port: 9000

spring:
  application:
    name: roses-monitor
  boot:
    admin:
      username: "${security.user.name}"       #These two are needed so that the client
      password: "${security.user.password}"   #can register at the protected server api
      client:
        metadata:
          user.name: "${security.user.name}"          #These two are needed so that the server
          user.password:  "${security.user.password}" #can access the proteceted client endpoints
  rabbitmq:
    host: 172.31.119.63
    port: 5672
    username: admin
    password: admin@dev
  cloud:
    bus:
      enabled: true
      trace:
        enabled: true

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh   # spring-cloud-bus刷新配置的请求路径

eureka:
  instance:
    metadata-map:
      user.name: "${security.user.name}"             #These two are needed so that the server
      user.password: "${security.user.password}"     #can access the protected client endpoints
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    registry-fetch-interval-seconds: 30
    service-url:
      defaultZone: http://localhost:8761/eureka

security:
  basic:
    enabled: true
  user:
    name: admin
    password: admin
